<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Version>0.0.0</Version>
        <AssemblyName>WinampNowPlayingToFile.$(MSBuildProjectName)</AssemblyName>
        <Authors>Ben Hutchison</Authors>
        <Copyright>© 2026 $(Authors)</Copyright>
        <Company>$(Authors)</Company>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <PackageProjectUrl>https://github.com/Aldaviva/WinampNowPlayingToFile</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Aldaviva/WinampNowPlayingToFile.git</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <Description>Interfaces and other abstractions used to write plugins that extend the functionality of WinampNowPlayingToFile</Description>
        <PackageTags>WinampNowPlayingToFile plugin abstraction addin extension</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeSource>true</IncludeSource>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <RootNamespace>WinampNowPlayingToFile</RootNamespace>
        <DevelopmentDependency>true</DevelopmentDependency>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.103" PrivateAssets="All" />
    </ItemGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true' or '$(Configuration)' != 'Debug'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

</Project>