name: MSBuild

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild /m /p:Configuration=Release WinampNowPlayingToFile.sln -t:build -restore
      
    - name: Prepare artifacts
      run: |
        mkdir ./artifact/
        copy Release/*.dll ./artifact/
        mkdir ./artifact/plugins/
        move ./artifact/gen_WinampNowPlayingToFile.dll ./artifact/plugins/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: WinampNowPlayingToFile
        path: ./artifact/
        if-no-files-found: error
