name: MSBuild

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install unmanaged dependencies
      run: |
        mkdir -Force -ErrorAction Ignore .\WinampNowPlayingToFile\bin\Release\
        copy .\packages\Daniel15.Sharpamp.1.0.0\Daniel15.Sharpamp.dll .\WinampNowPlayingToFile\bin\Release\

    - name: Build
      run: msbuild /m /p:Configuration=Release gen_WinampNowPlayingToFile -restore
      
    - name: Prepare artifacts
      run: |
        mkdir .\artifact\plugins\
        copy .\gen_WinampNowPlayingToFile\Release\*.dll .\artifact\
        move .\artifact\gen_WinampNowPlayingToFile.dll .\artifact\plugins\

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: WinampNowPlayingToFile
        path: .\artifact\
        if-no-files-found: error
