name: MSBuild

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Download Sharpamp installer
      run: Invoke-WebRequest -Uri "https://github.com/Daniel15/Sharpamp/releases/download/release-0.1.0/Sharpamp.0.1.Beta.exe" -OutFile Sharpamp.exe
    
    - name: Install Sharpamp
      run: |
        ./Sharpamp.exe /VERYSILENT /SP- /NORESTART /SUPPRESSMSGBOXES /LOG="Sharpamp.log"
        Get-Content Sharpamp.log
    
    - name: Build
      run: msbuild /m /p:Configuration=Release WinampNowPlayingToFile.sln -t:build -restore
      
    - name: Prepare artifacts
      run: |
        mkdir ./artifact/
        copy Release/*.dll ./artifact/
        mkdir ./artifact/plugins/
        move ./artifact/gen_WinampNowPlayingToFile.dll ./artifact/plugins/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: WinampNowPlayingToFile
        path: ./artifact/
        if-no-files-found: error
